$projectsDirPath 	= "Please enter projects dir path here."
$puttyDirPath	 	= "Please enter Putty dir path here."
$pageantKeysDirPath = "Please enter Pageant keys dir path here."
$gitUserName		= "Please enter username for Git."
$gitUserEmail 		= "Please enter user email for Git."